name: flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  path_provider: ^2.0.1
  sqflite: ^2.0.0+4
  intl: ^0.18.0
  table_calendar: ^3.0.0
  flutter_local_notifications: ^9.0.0+2
  timezone: ^0.8.0
  cloud_firestore: ^4.8.2
  google_sign_in: 6.2.2 # Added google_sign_in dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true